version: "3"

services:
  mysql:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    ports:
      - 3306:3306

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
